In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_startups.csv")

In [3]:
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [7]:
x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [8]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(categorical_features = [3])
x = one.fit_transform(x).toarray()

C:\Users\prads\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\prads\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
x_train.shape

NameError: name 'x_train' is not defined

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [12]:
regressor = Sequential()

In [13]:
x_train.shape

(40, 6)

In [39]:
regressor.add(Dense(units = 6,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [40]:
regressor.add(Dense(units = 7,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=7, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [41]:
regressor.add(Dense(units = 8,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [42]:
regressor.add(Dense(units = 9,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [43]:
regressor.add(Dense(units = 1,init = 'random_uniform'))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [44]:
regressor.compile (optimizer = 'adam',loss = 'mse',metrics = ['mse'])

In [45]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 170)

Epoch 1/170
40/40 [==============================] - 2s 38ms/step - loss: 13615990784.0000 - mean_squared_error: 13615990784.0000
Epoch 2/170
40/40 [==============================] - 0s 425us/step - loss: 13615976448.0000 - mean_squared_error: 13615976448.0000
Epoch 3/170
40/40 [==============================] - 0s 375us/step - loss: 13615948032.0000 - mean_squared_error: 13615948032.0000
Epoch 4/170
40/40 [==============================] - 0s 974us/step - loss: 13615888640.0000 - mean_squared_error: 13615888640.0000
Epoch 5/170
40/40 [==============================] - 0s 650us/step - loss: 13615781632.0000 - mean_squared_error: 13615781632.0000
Epoch 6/170
40/40 [==============================] - 0s 575us/step - loss: 13615597824.0000 - mean_squared_error: 13615597824.0000
Epoch 7/170
40/40 [==============================] - 0s 300us/step - loss: 13615285504.0000 - mean_squared_error: 13615285504.0000
Epoch 8/170
40/40 [==============================] - 0s 688us/step - loss: 136147299

40/40 [==============================] - 0s 525us/step - loss: 177589886.0000 - mean_squared_error: 177589886.0000
Epoch 127/170
40/40 [==============================] - 0s 450us/step - loss: 177098006.0000 - mean_squared_error: 177098006.0000
Epoch 128/170
40/40 [==============================] - 0s 550us/step - loss: 178080460.0000 - mean_squared_error: 178080460.0000
Epoch 129/170
40/40 [==============================] - 0s 425us/step - loss: 176113650.0000 - mean_squared_error: 176113650.0000
Epoch 130/170
40/40 [==============================] - 0s 500us/step - loss: 179100976.0000 - mean_squared_error: 179100976.0000
Epoch 131/170
40/40 [==============================] - 0s 375us/step - loss: 176907708.0000 - mean_squared_error: 176907708.0000
Epoch 132/170
40/40 [==============================] - 0s 350us/step - loss: 175174106.0000 - mean_squared_error: 175174106.0000
Epoch 133/170
40/40 [==============================] - 0s 425us/step - loss: 175675948.0000 - mean_squared_erro

In [46]:
y_pred = regressor.predict(x_test)

In [47]:
y_pred

array([[116365.43 ],
       [119471.74 ],
       [124441.9  ],
       [ 65145.734],
       [171558.27 ],
       [127810.805],
       [ 56516.977],
       [ 99466.6  ],
       [121300.54 ],
       [156726.   ]], dtype=float32)

In [48]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [49]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [50]:
accuracy

0.7545038851592614

model.save('regressor.h5')

In [ ]:
regressor.save('regressor.h5')

In [ ]:
x_train.shape

In [51]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

array([[58150.477]], dtype=float32)