In [9]:
list1 = [1,2,"john","45"]

In [10]:
import numpy as np
a = np.array(list1)

In [11]:
a

array(['1', '2', 'john', '45'], dtype='<U11')

In [12]:
a[2]

'john'

In [14]:
a[:3]

array(['1', '2', 'john'], dtype='<U11')

In [15]:
a[1:3]

array(['2', 'john'], dtype='<U11')

In [16]:
list1 = [[1,2,3],[4,5,6],[6,7,8],[8,9,10]]

In [17]:
type(list1)

list

In [47]:
a = np.array(list1)

In [19]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [50]:
a[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
a[1,1] = 25

In [32]:
a

array([[ 1,  2,  3],
       [ 4, 25,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [33]:
a[1:] =99

In [34]:
a

array([[ 1,  2,  3],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [29]:
a[1,1]

5

In [ ]:
a[[rows]],[coloumns]]

In [30]:
a[[0,1,2],[0,1,2]]

array([1, 5, 8])

In [21]:
a.ndim

2

In [22]:
a.shape

(4, 3)

In [23]:
a[0]

array([1, 2, 3])

In [24]:
a[1:3]

array([[4, 5, 6],
       [6, 7, 8]])

In [25]:
a[0:4,1:2]

array([[2],
       [5],
       [7],
       [9]])

In [46]:
a[1:3,1:]


array([[99, 99],
       [99, 99]])

In [35]:
list2 = np.array([[1,2,4],[6,7,8],[8,9,10]])

In [37]:
list2

array([[ 1,  2,  4],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [45]:
list2[0:2,2:3]

array([[4],
       [8]])

7

In [41]:
list2[2,0]

8

In [42]:
list2[[0,1,2],[0,1,0]]

array([1, 7, 8])

In [51]:
list3 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [52]:
list3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:

list3[[0,1,3,3],[0,0,0,3]]


array([ 0,  4, 12, 15])

In [54]:
list3[[0,1,3],[0]]


array([ 0,  4, 12])

In [55]:
list3[[0,1,3,3],[0,0,0,3]]


array([ 0,  4, 12, 15])

In [61]:
a = np.arange(10)

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a = np.arange(10,40)

In [64]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [67]:
a = np.arange(10,40,5)

In [68]:
a

array([10, 15, 20, 25, 30, 35])

In [167]:
a = np.zeros((3))

In [70]:
a

array([0., 0., 0.])

In [71]:
a = np.zeros((3,2))

In [72]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
a = np.ones((2,3))

In [78]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
a = np.eye(4)

In [82]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
a = np.linspace(10,20)

In [86]:
a

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [168]:
a = linspace(10,20,5)

In [169]:
a

array([10. , 12.5, 15. , 17.5, 20. ])

In [93]:
a.min()

10.0

In [94]:
a.argmin()

0

In [95]:
a.max()

20.0

In [96]:
a.argmax()

9

In [172]:
b = np.random.rand(4,2)

In [173]:
b

array([[0.44249443, 0.41293445],
       [0.11163463, 0.9635757 ],
       [0.22491774, 0.50335373],
       [0.10195401, 0.5099608 ]])

In [187]:
c = np.random.randint(100)

In [188]:
c

35

In [195]:
d = np.random.randint(1,100,1000)

In [196]:
d

array([11, 86, 59, 55, 47, 66, 91, 79, 81,  6, 31, 59, 33, 74, 36, 27, 29,
       16, 13,  9, 64, 93, 17, 37, 70, 85, 47, 84,  1, 99, 64, 89, 23, 89,
       57, 48, 23, 31, 13, 67, 31, 85, 43, 45, 21, 84, 49, 23, 96, 30,  9,
       93, 82, 93, 10, 85, 83, 28, 18, 92, 62, 35, 92, 36, 11, 21, 72, 81,
       44, 57, 72, 35, 65,  6, 10, 36, 14, 52, 93,  2, 51, 33, 43, 79, 46,
       88, 13, 54, 60, 20, 84, 36, 12,  2,  5, 38, 46,  5, 22, 26, 18, 73,
       59,  5, 32, 13, 85, 77, 91, 39, 50, 42,  9, 23, 42, 43, 12, 95, 52,
       29, 86, 95, 55, 49, 65, 90,  3, 91,  1,  1, 79, 79, 66,  8, 60, 75,
       86, 52, 29, 39, 35, 21, 75, 74, 67, 92, 70, 71, 58, 30, 24, 35, 26,
       39, 61, 37, 66, 27, 37, 37, 63,  3, 73, 94, 61, 41, 36, 25, 80,  2,
       76, 13,  6, 27, 97, 10,  6, 55, 93, 48, 31, 63, 22, 29, 99, 16, 11,
       67, 64, 22, 67, 41, 34,  5, 39,  7,  6, 89, 14, 55, 43, 26, 50, 75,
       45,  3, 33, 97, 50, 83, 46, 43, 54, 64,  9, 73, 90, 73, 28, 56, 22,
       19, 21,  8, 82, 19

In [135]:
f = np.arange(16)

In [136]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [197]:
g = f.reshape(4,4)

In [138]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [199]:
h = g.ravel()

In [203]:
h

array([ 0,  1,  2,  3,  4,  5, 45,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [209]:
h[15] = 135
h[2] = 16

In [210]:
h

array([  0,   1,  16,   3,   4,   5,  45,   7,   8,   9,  10,  11,  12,
        13,  14, 135])

In [211]:
g

array([[  0,   1,  16,   3],
       [  4,   5,  45,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 135]])

In [212]:
i =  g.flatten()

In [214]:
i[0] = 125

In [215]:
g

array([[  0,   1,  16,   3],
       [  4,   5,  45,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 135]])

In [216]:
k = g.T

In [217]:
k

array([[  0,   4,   8,  12],
       [  1,   5,   9,  13],
       [ 16,  45,  10,  14],
       [  3,   7,  11, 135]])

In [218]:
l = np.concatenate((g,k))

In [219]:
l

array([[  0,   1,  16,   3],
       [  4,   5,  45,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14, 135],
       [  0,   4,   8,  12],
       [  1,   5,   9,  13],
       [ 16,  45,  10,  14],
       [  3,   7,  11, 135]])

In [222]:
l = np.concatenate((g,k),axis=1)

In [224]:
l

array([[  0,   1,  16,   3,   0,   4,   8,  12],
       [  4,   5,  45,   7,   1,   5,   9,  13],
       [  8,   9,  10,  11,  16,  45,  10,  14],
       [ 12,  13,  14, 135,   3,   7,  11, 135]])

In [166]:
np.unique(l,return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 45]),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))

In [229]:
p = np.split(l,4)

In [230]:
p[0]

array([[ 0,  1, 16,  3,  0,  4,  8, 12]])

In [231]:
p[1]

array([[ 4,  5, 45,  7,  1,  5,  9, 13]])

In [232]:
p[2]

array([[ 8,  9, 10, 11, 16, 45, 10, 14]])

In [233]:
p[3]

array([[ 12,  13,  14, 135,   3,   7,  11, 135]])

In [234]:
p = np.split(l,4,axis=1)

In [235]:
p

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 16,   3],
        [ 45,   7],
        [ 10,  11],
        [ 14, 135]]), array([[ 0,  4],
        [ 1,  5],
        [16, 45],
        [ 3,  7]]), array([[  8,  12],
        [  9,  13],
        [ 10,  14],
        [ 11, 135]])]

In [236]:
p[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [237]:
p[1]

array([[ 16,   3],
       [ 45,   7],
       [ 10,  11],
       [ 14, 135]])

In [243]:
list6 = np.array([["ap","ts","bng","ke"],["ts","ke","l","d"],["ap","ts","l","ke"],["ke","ts","k","ke"]])

In [244]:
list6

array([['ap', 'ts', 'bng', 'ke'],
       ['ts', 'ke', 'l', 'd'],
       ['ap', 'ts', 'l', 'ke'],
       ['ke', 'ts', 'k', 'ke']], dtype='<U3')

In [247]:
np.unique(list6,return_counts=True)

(array(['ap', 'bng', 'd', 'k', 'ke', 'l', 'ts'], dtype='<U3'),
 array([2, 1, 1, 1, 5, 2, 4], dtype=int64))

In [248]:
arr = np.arange(0,10)

In [249]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
arr1 = arr-arr

In [255]:
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [257]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [258]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [259]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [260]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [262]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])