In [56]:
import pandas as pd
import numpy as np

In [57]:
dataset = pd.read_csv("churn_modelling.csv")

In [58]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave        619.0    France  Female   42   
1             2    15647311       Hill          NaN     Spain  Female   41   
2             3    15619304       Onio          NaN    France  Female   42   
3             4    15701354       Boni        699.0    France  Female   39   
4             5    15737888   Mitchell        850.0     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku        771.0    France    Male   39   
9996       9997    15569892  Johnstone        516.0    France    Male   35   
9997       9998    15584532        Liu        709.0    France  Female   36   
9998       9999    15682355  Sabbatini        772.0   Germany    Male   42   
9999      10000    15628319     Walker        792.0    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [59]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave        619.0    France  Female   42   
1          2    15647311      Hill          NaN     Spain  Female   41   
2          3    15619304      Onio          NaN    France  Female   42   
3          4    15701354      Boni        699.0    France  Female   39   
4          5    15737888  Mitchell        850.0     Spain  Female   43   
5          6    15574012       Chu        645.0     Spain    Male   44   
6          7    15592531  Bartlett        822.0    France    Male   50   
7          8    15656148    Obinna        376.0   Germany  Female   29   
8          9    15792365        He        501.0    France    Male   44   
9         10    15592389        H?        684.0    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [60]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore         True
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [61]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        2
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [62]:
dataset.fillna(dataset["CreditScore"].mean(), inplace = True)

In [63]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Geography"] = le.fit_transform(dataset["Geography"])
dataset["Gender"] = le.fit_transform(dataset["Gender"])

In [65]:
dataset

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602   Hargrave    619.00000          0       0   42   
1             2    15647311       Hill    650.54791          2       0   41   
2             3    15619304       Onio    650.54791          0       0   42   
3             4    15701354       Boni    699.00000          0       0   39   
4             5    15737888   Mitchell    850.00000          2       0   43   
...         ...         ...        ...          ...        ...     ...  ...   
9995       9996    15606229   Obijiaku    771.00000          0       1   39   
9996       9997    15569892  Johnstone    516.00000          0       1   35   
9997       9998    15584532        Liu    709.00000          0       0   36   
9998       9999    15682355  Sabbatini    772.00000          1       1   42   
9999      10000    15628319     Walker    792.00000          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [66]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave    619.00000          0       0   42   
1          2    15647311      Hill    650.54791          2       0   41   
2          3    15619304      Onio    650.54791          0       0   42   
3          4    15701354      Boni    699.00000          0       0   39   
4          5    15737888  Mitchell    850.00000          2       0   43   
5          6    15574012       Chu    645.00000          2       1   44   
6          7    15592531  Bartlett    822.00000          0       1   50   
7          8    15656148    Obinna    376.00000          1       0   29   
8          9    15792365        He    501.00000          0       1   44   
9         10    15592389        H?    684.00000          0       1   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [67]:
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [68]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(categorical_features = [1])
x = one.fit_transform(x).toarray()

S:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
S:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [69]:
# dataset.drop(["CustomerId","Surname"], axis = 1 inplace = True)

In [70]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [71]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [72]:
x.shape

(10000, 12)

In [73]:
x = x[:,1:]

In [74]:
x.shape

(10000, 11)

In [76]:
from sklearn.model_selection import train_test_split
x_train, y_train, x_test, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [77]:
x_train.shape

(8000, 11)

In [78]:
y_train.shape

(2000, 11)

In [79]:
x_test.shape

(8000,)

In [80]:
y_test.shape

(2000,)

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(y_train)

In [88]:
x_train

array([[-0.5698444 ,  1.74309049,  0.16936238, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30517139, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.1916312 , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.90141196, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62455054, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28430214, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [89]:
x_test

array([[ 1.00000000e+00, -1.09065534e-16,  5.97000000e+02, ...,
         1.00000000e+00,  1.00000000e+00,  1.92852670e+05],
       [-3.63181707e-16, -1.09065534e-16,  5.23000000e+02, ...,
         1.00000000e+00,  2.78665979e-17,  1.28702100e+05],
       [-3.63181707e-16,  1.00000000e+00,  7.06000000e+02, ...,
         1.00000000e+00,  1.00000000e+00,  7.57322500e+04],
       ...,
       [-3.63181707e-16,  1.00000000e+00,  5.78000000e+02, ...,
         1.00000000e+00,  2.78665979e-17,  1.41533190e+05],
       [ 1.00000000e+00, -1.09065534e-16,  6.50000000e+02, ...,
         1.00000000e+00,  1.00000000e+00,  1.12764800e+04],
       [ 1.00000000e+00, -1.09065534e-16,  5.73000000e+02, ...,
         1.00000000e+00,  2.78665979e-17,  1.92950600e+05]])

# Formula for Standard Scaling 
x - mean/ std