In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_startups.csv")

In [3]:
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [7]:
x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [8]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(categorical_features = [3])
x = one.fit_transform(x).toarray()

S:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
S:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
# x_train.shape

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [12]:
regressor = Sequential()

In [13]:
x_train.shape

(40, 6)

In [14]:
regressor.add(Dense(units = 6,init = 'random_uniform',activation = 'relu'))

S:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [15]:
regressor.add(Dense(units = 3,init = 'random_uniform',activation = 'relu'))

S:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [16]:
# regressor.add(Dense(units = 8,init = 'random_uniform',activation = 'relu'))

In [17]:
# regressor.add(Dense(units = 9,init = 'random_uniform',activation = 'relu'))

In [18]:
regressor.add(Dense(units = 1,init = 'random_uniform'))

S:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [19]:
regressor.compile (optimizer = 'adam',loss = 'mse',metrics = ['mse'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [20]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 170)


Epoch 1/170
40/40 [==============================] - 0s 8ms/step - loss: 13611063552.0000 - mse: 13611063296.0000
Epoch 2/170
40/40 [==============================] - 0s 399us/step - loss: 13607444736.0000 - mse: 13607445504.0000
Epoch 3/170
40/40 [==============================] - 0s 200us/step - loss: 13602276096.0000 - mse: 13602276352.0000
Epoch 4/170
40/40 [==============================] - 0s 274us/step - loss: 13595920896.0000 - mse: 13595920384.0000
Epoch 5/170
40/40 [==============================] - 0s 225us/step - loss: 13587859200.0000 - mse: 13587859456.0000
Epoch 6/170
40/40 [==============================] - 0s 349us/step - loss: 13576840448.0000 - mse: 13576840192.0000
Epoch 7/170
40/40 [==============================] - 0s 299us/step - loss: 13564048512.0000 - mse: 13564048384.0000
Epoch 8/170
40/40 [==============================] - 0s 449us/step - loss: 13547738368.0000 - mse: 13547738112.0000
Epoch 9/170
40/40 [==============================] - 0s 399us/step - loss

In [21]:
y_pred = regressor.predict(x_test)

In [22]:
y_pred

array([[105355.61 ],
       [116962.195],
       [118719.41 ],
       [ 72514.82 ],
       [172073.89 ],
       [142454.33 ],
       [ 68776.23 ],
       [ 87602.13 ],
       [130292.56 ],
       [156038.23 ]], dtype=float32)

In [23]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [24]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [25]:
accuracy

0.6837952566919291

model.save('regressor.h5')

In [26]:
regressor.save('regressor.h5')

In [27]:
x_train.shape

(40, 6)

In [28]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

array([[50580.207]], dtype=float32)